import { Category, Product, Combo, Testimonial, Recipe } from '@/types'

export const categories: Category[] = [
  {
    id: 'cat-1',
    name: 'Cítricos',
    slug: 'citricos',
    description: 'Limón y naranja deshidratados con sabor intenso',
  },
  {
    id: 'cat-2',
    name: 'Tropicales',
    slug: 'tropicales',
    description: 'Piña, toronja, fresa, guayaba y kiwi premium',
  },
  {
    id: 'cat-3',
    name: 'Mix Enchilado',
    slug: 'mix-enchilado',
    description: 'La combinación perfecta con el toque picante que enamora',
  },
]

export const products: Product[] = [
  {
    id: 'prod-1',
    slug: 'limon-deshidratado-100g',
    name: 'Limón Deshidratado 100g',
    shortName: 'Limón',
    description: 'El antojito ácido que no puedes parar de comer.',
    longDescription:
      'Nuestro limón deshidratado captura toda la intensidad del limón mexicano en cada rebanada. Sin conservadores, sin aditivos — solo el sabor puro de la fruta bajo el sol del Pacífico. El snack perfecto para los amantes de lo ácido.',
    price: 65,
    comparePrice: undefined,
    weight: '100g',
    category: 'Cítricos',
    categorySlug: 'citricos',
    tags: ['popular', 'dulce'],
    ingredients: 'Limón 100% natural. Sin conservadores ni aditivos.',
    benefits: [
      'Alto en vitamina C',
      'Ayuda a la digestión',
      'Sin conservadores',
      'Antioxidante natural',
    ],
    image: '/images/limon.jpg',
    images: ['/images/limon.jpg', '/images/manzana.jpg'],
    inStock: true,
    rating: 4.8,
    reviewCount: 124,
    emoji: '🍋',
    pairsWith: ['prod-2', 'prod-7'],
  },
  {
    id: 'prod-2',
    slug: 'naranja-deshidratada-100g',
    name: 'Naranja Deshidratada 100g',
    shortName: 'Naranja',
    description: 'Dulce, vibrante y llena de vitaminas para tu día.',
    longDescription:
      'Rodajas de naranja deshidratada con toda su dulzura natural. Perfectas solas, en tus aguas, cocteles o simplemente como snack de media tarde. Cada rodaja es sol concentrado.',
    price: 65,
    comparePrice: undefined,
    weight: '100g',
    category: 'Cítricos',
    categorySlug: 'citricos',
    tags: ['recomendado', 'dulce'],
    ingredients: 'Naranja 100% natural. Sin conservadores ni aditivos.',
    benefits: [
      'Rica en vitamina C y D',
      'Energía natural',
      'Sin azúcar añadida',
      'Perfecta para cocteles',
    ],
    image: '/images/naranja.jpg',
    images: ['/images/naranja.jpg'],
    inStock: true,
    rating: 4.7,
    reviewCount: 98,
    emoji: '🍊',
    pairsWith: ['prod-1', 'prod-3'],
  },
  {
    id: 'prod-3',
    slug: 'pina-deshidratada-100g',
    name: 'Piña Deshidratada 100g',
    shortName: 'Piña',
    description: 'Tropical, dulce y el favorito de los que buscan energía.',
    longDescription:
      'La piña deshidratada concentra todo el sabor tropical en un snack ligero y adictivo. Ideal para deportistas, oficina o simplemente para darte un gustito natural sin culpa.',
    price: 75,
    comparePrice: undefined,
    weight: '100g',
    category: 'Tropicales',
    categorySlug: 'tropicales',
    tags: ['popular', 'dulce'],
    ingredients: 'Piña 100% natural. Sin conservadores ni aditivos.',
    benefits: [
      'Bromelina natural',
      'Energía sostenida',
      'Anti-inflamatoria',
      'Ideal post-ejercicio',
    ],
    image: '/images/pina.jpg',
    images: ['/images/pina.jpg', '/images/pina-hero.jpg'],
    inStock: true,
    rating: 4.9,
    reviewCount: 210,
    emoji: '🍍',
    pairsWith: ['prod-7', 'prod-4'],
  },
  {
    id: 'prod-4',
    slug: 'toronja-deshidratada-100g',
    name: 'Toronja Deshidratada 100g',
    shortName: 'Toronja',
    description: 'Amargo, ácido y brutalmente delicioso. Para paladares aventureros.',
    longDescription:
      'La toronja deshidratada tiene un sabor único: un balance perfecto entre ácido y amargo que engancha. Úsala en cocteles de mezcal, aguas frescas o disfrútala sola para una experiencia intensa.',
    price: 75,
    comparePrice: undefined,
    weight: '100g',
    category: 'Tropicales',
    categorySlug: 'tropicales',
    tags: ['nuevo', 'dulce'],
    ingredients: 'Toronja 100% natural. Sin conservadores ni aditivos.',
    benefits: [
      'Antioxidante potente',
      'Ayuda al metabolismo',
      'Sin azúcar añadida',
      'Perfecta para mezcal',
    ],
    image: '/images/toronja.jpg',
    images: ['/images/toronja.jpg'],
    inStock: true,
    rating: 4.6,
    reviewCount: 67,
    emoji: '🍊',
    pairsWith: ['prod-1', 'prod-2'],
  },
  {
    id: 'prod-5',
    slug: 'fresa-deshidratada-100g',
    name: 'Fresa Deshidratada 100g',
    shortName: 'Fresa',
    description: 'El sabor de la fresa en su máxima expresión. Dulce sin remordimientos.',
    longDescription:
      'Fresas mexicanas seleccionadas, deshidratadas para capturar toda su esencia. El snack favorito de los que no pueden resistirse a lo dulce — pero quieren hacerlo bien.',
    price: 75,
    comparePrice: undefined,
    weight: '100g',
    category: 'Tropicales',
    categorySlug: 'tropicales',
    tags: ['popular', 'recomendado', 'dulce'],
    ingredients: 'Fresa 100% natural. Sin conservadores ni aditivos.',
    benefits: [
      'Rica en antioxidantes',
      'Alto en vitamina C',
      'Sin colorantes',
      'Baja en calorías',
    ],
    image: '/images/fresa.jpg',
    images: ['/images/fresa.jpg'],
    inStock: true,
    rating: 5.0,
    reviewCount: 189,
    emoji: '🍓',
    pairsWith: ['prod-6', 'prod-3'],
  },
  {
    id: 'prod-6',
    slug: 'guayaba-deshidratada-100g',
    name: 'Guayaba Deshidratada 100g',
    shortName: 'Guayaba',
    description: 'El sabor de la infancia en un snack moderno y saludable.',
    longDescription:
      'La guayaba deshidratada trae de vuelta ese sabor nostálgico de la fruta mexicana. Concentrada, aromática y con una textura que enamora. Un snack que conecta con tus raíces.',
    price: 75,
    comparePrice: undefined,
    weight: '100g',
    category: 'Tropicales',
    categorySlug: 'tropicales',
    tags: ['recomendado', 'dulce'],
    ingredients: 'Guayaba 100% natural. Sin conservadores ni aditivos.',
    benefits: [
      'La fruta más rica en vitamina C',
      'Fibra natural',
      'Sabor único mexicano',
      'Sin conservadores',
    ],
    image: '/images/guayaba.jpg',
    images: ['/images/guayaba.jpg'],
    inStock: true,
    rating: 4.8,
    reviewCount: 143,
    emoji: '🍈',
    pairsWith: ['prod-5', 'prod-3'],
  },
  {
    id: 'prod-7',
    slug: 'kiwi-deshidratado-100g',
    name: 'Kiwi Deshidratado 100g',
    shortName: 'Kiwi',
    description: 'Exótico, ácido y visualmente irresistible. El snack instagrameable.',
    longDescription:
      'El kiwi deshidratado es el snack que impresiona: un verde vibrante, sabor intenso y textura perfecta. Rico en nutrientes y con ese toque ácido que lo hace adictivo. El snack que todos van a querer probar.',
    price: 75,
    comparePrice: undefined,
    weight: '100g',
    category: 'Tropicales',
    categorySlug: 'tropicales',
    tags: ['nuevo', 'dulce'],
    ingredients: 'Kiwi 100% natural. Sin conservadores ni aditivos.',
    benefits: [
      'Alto en vitamina K',
      'Digestivo natural',
      'Rico en fibra',
      'Color natural vibrante',
    ],
    image: '/images/kiwi.jpg',
    images: ['/images/kiwi.jpg'],
    inStock: true,
    rating: 4.7,
    reviewCount: 82,
    emoji: '🥝',
    pairsWith: ['prod-5', 'prod-3'],
  },
  {
    id: 'prod-8',
    slug: 'mix-enchilado-50g',
    name: 'Mix Enchilado 50g',
    shortName: 'Mix Enchilado',
    description: '¡El antojito número 1! Piña, manzana y mango con chili y limón.',
    longDescription:
      'Nuestro mix enchilado es la combinación perfecta: la dulzura de la piña, manzana y mango encontrando al picante. Inspirado en los antojitos callejeros de México, pero con ingredientes 100% naturales y sin conservadores. Advertencia: altamente adictivo.',
    price: 50,
    comparePrice: undefined,
    weight: '50g',
    category: 'Mix Enchilado',
    categorySlug: 'mix-enchilado',
    tags: ['popular', 'recomendado', 'enchilado'],
    ingredients:
      'Piña deshidratada, manzana deshidratada, mango deshidratado, chile en polvo, limón en polvo. Sin conservadores.',
    benefits: [
      'El antojito perfecto',
      'Sabor callejero premium',
      'Sin conservadores',
      'Energía + picante natural',
    ],
    image: '/images/mixenchilado.jpg',
    images: ['/images/mixenchilado.jpg', '/images/mix.jpg', '/images/manzana.jpg'],
    inStock: true,
    rating: 5.0,
    reviewCount: 312,
    emoji: '🌶️',
    pairsWith: ['prod-3', 'prod-5'],
  },
]

export const combos: Combo[] = [
  {
    id: 'combo-1',
    slug: 'pack-energetico',
    name: 'Pack Energético',
    description: 'Los 3 favoritos para tener energía todo el día. Perfecto para deportistas y oficina.',
    products: [
      { productId: 'prod-3', quantity: 1 },
      { productId: 'prod-5', quantity: 1 },
      { productId: 'prod-7', quantity: 1 },
    ],
    price: 180,
    originalPrice: 225,
    savings: 45,
    savingsPercent: 20,
    image: '/images/pina.jpg',
    emoji: '⚡',
    tag: 'Más vendido',
  },
  {
    id: 'combo-2',
    slug: 'pack-botanero',
    name: 'Pack Botanero',
    description: 'Para botanear sin culpa: cítricos + mix enchilado. El combo de la reunión.',
    products: [
      { productId: 'prod-1', quantity: 1 },
      { productId: 'prod-2', quantity: 1 },
      { productId: 'prod-8', quantity: 2 },
    ],
    price: 195,
    originalPrice: 245,
    savings: 50,
    savingsPercent: 20,
    image: '/images/mixenchilado.jpg',
    emoji: '🎉',
    tag: 'Ideal para fiestas',
  },
  {
    id: 'combo-3',
    slug: 'pack-semanal',
    name: 'Pack Semanal',
    description: 'Un snack diferente cada día. 5 productos para tu semana completa.',
    products: [
      { productId: 'prod-1', quantity: 1 },
      { productId: 'prod-3', quantity: 1 },
      { productId: 'prod-5', quantity: 1 },
      { productId: 'prod-6', quantity: 1 },
      { productId: 'prod-8', quantity: 1 },
    ],
    price: 295,
    originalPrice: 375,
    savings: 80,
    savingsPercent: 21,
    image: '/images/pina-hero.jpg',
    emoji: '📅',
    tag: 'Ahorra más',
  },
  {
    id: 'combo-4',
    slug: 'pack-coctelero',
    name: 'Pack Coctelero',
    description: 'Naranja, toronja y limón para elevar tus cocteles y aguas. Bartender level.',
    products: [
      { productId: 'prod-1', quantity: 1 },
      { productId: 'prod-2', quantity: 1 },
      { productId: 'prod-4', quantity: 1 },
    ],
    price: 165,
    originalPrice: 205,
    savings: 40,
    savingsPercent: 20,
    image: '/images/kiwi.jpg',
    emoji: '🍹',
    tag: 'Para bartenders',
  },
]

export const testimonials: Testimonial[] = [
  {
    id: 'test-1',
    name: 'Sofía Ramírez',
    location: 'CDMX',
    rating: 5,
    text: 'El mix enchilado es una locura. Lo pedí por primera vez para una reunión y mis amigos me pidieron el contacto de dónde lo compré. Ya llevo 3 pedidos este mes 🔥',
    product: 'Mix Enchilado',
    avatar: 'SR',
  },
  {
    id: 'test-2',
    name: 'Carlos Mendoza',
    location: 'Guadalajara',
    rating: 5,
    text: 'Llevo meses buscando fruta deshidratada sin conservadores y por fin la encontré. La fresa es increíble, sabe exactamente a fresa fresca pero concentrada.',
    product: 'Fresa Deshidratada',
    avatar: 'CM',
  },
  {
    id: 'test-3',
    name: 'Ana Belén Torres',
    location: 'Monterrey',
    rating: 5,
    text: 'Compré el Pack Energético para el gym y es perfecto. Ya no llevo barras procesadas, con esto tengo energía de verdad y natural. Súper recomendado.',
    product: 'Pack Energético',
    avatar: 'AT',
  },
  {
    id: 'test-4',
    name: 'Rodrigo Vega',
    location: 'Cancún',
    rating: 5,
    text: 'El pack coctelero lo usé para una fiesta en mi casa. Las rodajas de naranja y toronja en los cocteles quedaron increíbles. Todos me preguntaron dónde las compré.',
    product: 'Pack Coctelero',
    avatar: 'RV',
  },
  {
    id: 'test-5',
    name: 'Mariana López',
    location: 'Puebla',
    rating: 5,
    text: 'La guayaba deshidratada me recuerda a mi infancia pero en versión premium. No tiene colorantes, no tiene nada raro. Solo guayaba pura. 10/10.',
    product: 'Guayaba Deshidratada',
    avatar: 'ML',
  },
  {
    id: 'test-6',
    name: 'Héctor Ávila',
    location: 'Oaxaca',
    rating: 5,
    text: 'Pedí por WhatsApp y llegó rapidísimo. El empaque es bonito, el producto fresco. El limón deshidratado está insanamente bueno con mezcal. Nueva adicción.',
    product: 'Limón Deshidratado',
    avatar: 'HA',
  },
]

export const recipes: Recipe[] = [
  {
    id: 'rec-1',
    slug: 'agua-fresca-naranja-menta',
    title: 'Agua Fresca de Naranja y Menta',
    description: 'Refrescante, natural y llena de vitaminas. Lista en 5 minutos.',
    prepTime: '5 min',
    difficulty: 'Fácil',
    ingredients: [
      '3 rodajas de Naranja Deshidratada FrutaPacífico',
      '1 litro de agua fría',
      '5 hojas de menta fresca',
      'Hielo al gusto',
      'Endulzante natural (opcional)',
    ],
    steps: [
      'Coloca las rodajas de naranja deshidratada en una jarra con el agua.',
      'Agrega las hojas de menta y deja reposar 10 minutos para que libere su sabor.',
      'Añade hielo y sirve. La naranja se puede comer después.',
      'Opcional: agrega unas gotas de limón para un toque extra.',
    ],
    image: '/images/pina-hero.jpg',
    emoji: '🍊',
    category: 'bebida',
    products: ['prod-2'],
  },
  {
    id: 'rec-2',
    slug: 'coctel-mezcal-toronja',
    title: 'Coctel de Mezcal con Toronja',
    description: 'El trago perfecto para impresionar. Amargo, fuerte y muy mexicano.',
    prepTime: '5 min',
    difficulty: 'Fácil',
    ingredients: [
      '2 rodajas de Toronja Deshidratada FrutaPacífico',
      '1 rodaja de Limón Deshidratado FrutaPacífico',
      '60ml de mezcal',
      '30ml de jugo de toronja natural',
      'Sal de gusano para el borde',
      'Hielo',
    ],
    steps: [
      'Escarcha el borde del vaso con sal de gusano y limón.',
      'En la coctelera: mezcal + jugo de toronja + hielo. Agita 15 segundos.',
      'Sirve en el vaso escarachado.',
      'Decora con las rodajas de toronja y limón deshidratados. ¡Listo!',
    ],
    image: '/images/kiwi.jpg',
    emoji: '🍹',
    category: 'coctel',
    products: ['prod-4', 'prod-1'],
  },
  {
    id: 'rec-3',
    slug: 'yogurt-con-fruta-deshidratada',
    title: 'Yogurt Bowl con Frutas del Pacífico',
    description: 'El desayuno premium que te va a llenar de energía y te va a hacer sentir bien.',
    prepTime: '5 min',
    difficulty: 'Fácil',
    ingredients: [
      '1 taza de yogurt griego natural',
      '2 rodajas de Piña Deshidratada FrutaPacífico',
      '3 trozos de Fresa Deshidratada FrutaPacífico',
      '1 cucharada de granola',
      'Miel al gusto',
    ],
    steps: [
      'Sirve el yogurt en un tazón.',
      'Coloca encima las frutas deshidratadas.',
      'Agrega la granola y un chorrito de miel.',
      'Opciones extra: chia, coco rallado o kiwi deshidratado.',
    ],
    image: '/images/pina.jpg',
    emoji: '🥣',
    category: 'snack',
    products: ['prod-3', 'prod-5'],
  },
  {
    id: 'rec-4',
    slug: 'trail-mix-energetico',
    title: 'Trail Mix Energético con Mix Enchilado',
    description: 'Tu snack de gym, trabajo o aventura. Energía y sabor sin culpa.',
    prepTime: '3 min',
    difficulty: 'Fácil',
    ingredients: [
      '1 bolsa de Mix Enchilado FrutaPacífico',
      '¼ taza de almendras naturales',
      '¼ taza de nuez de la india',
      '2 cucharadas de arándanos',
      '1 cucharada de coco rallado',
    ],
    steps: [
      'Mezcla todos los ingredientes en un tazón o bolsa zip.',
      'Divide en porciones para la semana.',
      'Guarda en lugar fresco y seco.',
      'El mix enchilado le da el toque picante perfecto que transforma todo.',
    ],
    image: '/images/mixenchilado.jpg',
    emoji: '🌶️',
    category: 'snack',
    products: ['prod-8'],
  },
]

export const getProductById = (id: string) => products.find((p) => p.id === id)
export const getProductBySlug = (slug: string) => products.find((p) => p.slug === slug)
export const getComboById = (id: string) => combos.find((c) => c.id === id)
export const getComboBySlug = (slug: string) => combos.find((c) => c.slug === slug)
export const getProductsByCategory = (categorySlug: string) =>
  products.filter((p) => p.categorySlug === categorySlug)
export const getBestSellers = () => products.filter((p) => p.tags.includes('popular'))
export const getNewProducts = () => products.filter((p) => p.tags.includes('nuevo'))
